#!/usr/bin/bash

set -eu

help() {
    cat <<EOF 
KCT

usage: $0 [OPTIONS] <PROGRAM>

Options:
    -h|--help     Show the usage details
    -n|--name     Set an alias name
    -d|--down     Kill the given program
    -l|--list     List all opened programs
    -u|--update   Update the script automatically

Example:
    kct discord
    kct -n hell discord
    kct -d hell
    kct -u
    kct -l
    kct -h
EOF
}

open() {
    $@ &> /dev/null &
    echo $!
}

down() {
    kill -9 $(cat /tmp/kct/$1.pid)
}

savepid() {
    mkdir -p "/tmp/kct"
    echo $1 > "/tmp/kct/$2.pid"
}

stillrunning() {
    kill -0 "$1" >/dev/null 2>&1
}

list() {
    for prog in $(ls /tmp/kct); do
        pid=$(cat /tmp/kct/$prog)

        if ! $(stillrunning $pid); then
            rm /tmp/kct/$prog
            continue
        fi

        echo "[$pid] $prog"
    done
}

autoupdate() {
    local src="https://raw.githubusercontent.com/SadS4ndWiCh/kct/refs/heads/main/kct?cache=$(date +%s)"
    latestcode="$(curl -s -L $src)"
    if [ ! $? -eq 0 ]; then
        echo "[*] failed to update"
        return 0
    fi

    scriptpath=$(realpath $0)
    localcode="$(cat $scriptpath)"

    checksum=$(echo -n $localcode | sha256sum | awk '{print $1}')
    latestchecksum=$(echo -n $latestcode | sha256sum | awk '{print $1}')

    if [[ $checksum = $latestchecksum ]]; then
        echo "[+] already updated"
        return 1
    fi

    if [ -w $scriptpath ]; then
        echo "$latestcode" > $scriptpath
        echo "[+] new update installed"
    else
        echo "$latestcode" | sudo tee $scriptpath > /dev/null
        echo "[+] new update installed"
    fi
}

if [[ $# -eq 0 ]]; then
    help
    exit
fi

mkdir -p /tmp/kct

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -h|--help)
            help
            exit
            ;;
        -l|--list)
            list
            exit
            ;;
        -d|--down)
            DOWN=true
            shift
            ;;
        -n|--name)
            PROGRAM_ALIAS=$2
            shift
            shift
            ;;
        -u|--update)
            autoupdate
            exit
            ;;
        *)
            break
            ;;
    esac
done

if [[ ! -v PROGRAM_ALIAS ]]; then
    PROGRAM_ALIAS=$1
fi

if [[ -v DOWN ]]; then
    kill -9 $(cat "/tmp/kct/$PROGRAM_ALIAS.pid")
    exit
fi

PID=$(open $@)
savepid $PID $PROGRAM_ALIAS
